### ISSUE TITLE
randomized traffic only spawns taxis when Open Limit Adjuster is installed.

### ISSUE THREAD

**Issue by PentiumMMX166** [GTAMadman/GTA-III-Rainbomizer#3]
i only see taxi cabs spawn instead of random vehicles on the streets, i don't know why it's happening, i restarted gta 3 and the same results.

**Comment by GTAMadman** [comment]
Hello, I'm not sure why Limit Adjuster would be causing that. Depending on what other mods you have installed, Limit Adjuster is not required for Rainbomizer if you are only using this mod, though I will look into this. Thanks.

**Comment by PentiumMMX166** [comment]
i am using open limit adjuster for Project 2Dfx. the conflict doesn't happen on Vice City or San Andreas with their versions of the rainbomizer mod on there.

**Comment by GTAMadman** [comment]
Added a fix for this issue, will be released in next update.
