### ISSUE TITLE
Spawns boats and aircrafts on the road

### ISSUE THREAD

**Issue by ner00** [GTAMadman/GTA-III-Rainbomizer#4]
The aircrafts may be related to having the aircrafts mod installed and not being accounted for in the exclusions list, but the boats don't make any sense.

**Comment by GTAMadman** [comment]
Hello, if the aircraft you are talking about is the "AirTrain" which is seen at the airport, this can be disabled by opening the configuration file `Rainbomizer.cfg` searching for "AirTrain" then changing it to `AirTrain = false`.

As for boats in traffic, a similar option will soon be added to enable/disable certain vehicles which can spawn in traffic. Thanks.

**Comment by ner00** [comment]
Yeah, it's spawning in traffic, as well as other vehicles like trains, etc.

**Comment by GTAMadman** [comment]
Added config options to disable certain traffic vehicles, will be released in next update.
